name: registry_scripts
description: Scripts for managing the UI Market registry
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.0
  http: ^1.1.0
  archive: ^3.3.7
